"""HTML report writer — a self-contained, professional-looking summary page."""

from __future__ import annotations

import html
from pathlib import Path

from reports.models import RunReport, StageResult, Status, StepResult
from utils.timing import format_duration

ASSETS_DIR = Path(__file__).resolve().parent.parent / "assets"

_LABEL_CLASS = {Status.PASS: "pass", Status.WARN: "warn", Status.FAIL: "fail"}


def _step_html(step: StepResult) -> str:
    css = step.status.value
    detail = f'<div class="step-detail">{html.escape(step.detail)}</div>' if step.detail else ""
    return (
        f'<div class="step {css}">'
        f'<div class="icon">{step.status.symbol}</div>'
        f'<div><div>{html.escape(step.name)}</div>{detail}</div>'
        f'<div class="step-duration">{format_duration(step.duration_s)}</div>'
        f"</div>"
    )


def _stage_html(stage: StageResult) -> str:
    steps_html = "\n".join(_step_html(step) for step in stage.steps)
    return (
        f'<section class="stage">'
        f'<div class="stage-header"><span>{html.escape(stage.name)}</span>'
        f'<span>{stage.status.symbol} {stage.status.value.upper()} · {format_duration(stage.duration_s)}</span></div>'
        f"{steps_html}"
        f"</section>"
    )


def write_html_report(report: RunReport, path: Path) -> Path:
    css = (ASSETS_DIR / "report.css").read_text(encoding="utf-8")
    badge_class = _LABEL_CLASS.get(report.overall_status, "fail")
    stages_html = "\n".join(_stage_html(stage) for stage in report.stages)

    passed_steps = sum(1 for _, s in report.all_steps() if s.status is Status.PASS)
    total_steps = sum(1 for _, s in report.all_steps() if s.status is not Status.SKIP)

    document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Launch Readiness Report — {html.escape(report.environment)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>{css}</style>
</head>
<body>
<header>
  <h1>Launch Readiness Report</h1>
  <p>{html.escape(report.environment)} · {report.started_at.strftime('%Y-%m-%d %H:%M UTC')}</p>
  <span class="badge {badge_class}">{html.escape(report.readiness_label)}</span>
</header>

<div class="meta-grid">
  <div><div class="label">Readiness score</div><div class="value">{report.score}%</div></div>
  <div><div class="label">Steps passed</div><div class="value">{passed_steps}/{total_steps}</div></div>
  <div><div class="label">Duration</div><div class="value">{format_duration(report.duration_s)}</div></div>
  <div><div class="label">Stages</div><div class="value">{len(report.stages)}</div></div>
</div>

{stages_html}

<footer>Generated by the Drywall Toolbox Launch Readiness Validation Suite.</footer>
</body>
</html>
"""
    path.write_text(document, encoding="utf-8")
    return path
