<?php
/**
 * Stripe Express Checkout shipping-rate readiness hardening.
 *
 * The official WooCommerce Stripe extension owns Express Checkout Element
 * options, wallet events, shipping-address collection, shipping-rate selection,
 * amount updates, confirmation, and cancellation. This boundary only ensures a
 * verified wallet address update cannot reuse a stale WooCommerce package-rate
 * cache and records redacted diagnostics when WooCommerce still returns no rate.
 *
 * @package drywall-toolbox
 */

defined( 'ABSPATH' ) || exit;

final class DTB_ExpressCheckoutShippingReadiness {
	private const EXPRESS_HEADER       = 'x-wcstripe-express-checkout';
	private const EXPRESS_NONCE_HEADER = 'x-wcstripe-express-checkout-nonce';
	private const EXPRESS_NONCE_ACTION = 'wc_store_api_express_checkout';

	/** @var array<int,string> */
	private const ADDRESS_UPDATE_ROUTES = [
		'/wc/store/v1/cart/update-customer',
		'/wc/store/cart/update-customer',
	];

	/** @var array<int,string> */
	private const OBSERVED_ROUTES = [
		'/wc/store/v1/cart/update-customer',
		'/wc/store/v1/cart/select-shipping-rate',
		'/wc/store/v1/checkout',
		'/wc/store/cart/update-customer',
		'/wc/store/cart/select-shipping-rate',
		'/wc/store/checkout',
	];

	public static function register(): void {
		add_filter( 'rest_pre_dispatch', [ __CLASS__, 'prepare_address_update' ], 8, 3 );
		add_filter( 'rest_request_after_callbacks', [ __CLASS__, 'observe_shipping_response' ], 30, 3 );
	}

	/**
	 * Clear only WooCommerce's package-rate cache before the verified wallet
	 * address is applied. WooCommerce remains responsible for updating the
	 * customer, calculating packages, selecting rates, taxes, and totals.
	 *
	 * @param mixed           $response Existing pre-dispatch response.
	 * @param WP_REST_Server  $server   REST server instance.
	 * @param WP_REST_Request $request  Current request.
	 * @return mixed
	 */
	public static function prepare_address_update( $response, WP_REST_Server $server, WP_REST_Request $request ) {
		unset( $server );

		if ( null !== $response || ! self::is_verified_request( $request ) ) {
			return $response;
		}

		if ( ! in_array( $request->get_route(), self::ADDRESS_UPDATE_ROUTES, true ) ) {
			return $response;
		}

		if ( function_exists( 'wc_load_cart' ) && ( ! function_exists( 'WC' ) || ! WC()->cart || ! WC()->session ) ) {
			wc_load_cart();
		}

		if ( ! function_exists( 'WC' ) || ! WC()->cart ) {
			return $response;
		}

		$packages = (array) WC()->cart->get_shipping_packages();
		if ( function_exists( 'dtb_commerce_invalidate_shipping_package_cache' ) ) {
			dtb_commerce_invalidate_shipping_package_cache( $packages );
		}

		return $response;
	}

	/**
	 * Record only route/status/rate-count diagnostics. Wallet payloads, names,
	 * addresses, email, phone, and payment data are never logged.
	 *
	 * @param mixed           $response Response generated by the route callback.
	 * @param mixed           $handler  Route handler metadata.
	 * @param WP_REST_Request $request  Current request.
	 * @return mixed
	 */
	public static function observe_shipping_response( $response, $handler, WP_REST_Request $request ) {
		unset( $handler );

		if ( ! self::is_verified_request( $request ) || ! in_array( $request->get_route(), self::OBSERVED_ROUTES, true ) ) {
			return $response;
		}

		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$status = $response instanceof WP_REST_Response ? (int) $response->get_status() : 200;
		if ( $status < 200 || $status >= 300 ) {
			return $response;
		}

		$data = $response instanceof WP_REST_Response ? $response->get_data() : $response;
		if ( ! is_array( $data ) || ! self::response_needs_shipping( $data ) ) {
			return $response;
		}

		$rate_count = self::shipping_rate_count( $data );
		if ( $rate_count > 0 ) {
			return $response;
		}

		self::log_failure(
			'stripe_express_checkout_shipping_rates_missing',
			[
				'route'      => sanitize_text_field( $request->get_route() ),
				'status'     => $status,
				'rate_count' => 0,
			]
		);

		return $response;
	}

	private static function is_verified_request( WP_REST_Request $request ): bool {
		$route = $request->get_route();
		if ( ! str_starts_with( $route, '/wc/store/v1/cart' )
			&& ! str_starts_with( $route, '/wc/store/v1/checkout' )
			&& ! str_starts_with( $route, '/wc/store/cart' )
			&& ! str_starts_with( $route, '/wc/store/checkout' ) ) {
			return false;
		}

		$context = strtolower( sanitize_text_field( (string) $request->get_header( self::EXPRESS_HEADER ) ) );
		if ( 'true' !== $context ) {
			return false;
		}

		$nonce = sanitize_text_field( (string) $request->get_header( self::EXPRESS_NONCE_HEADER ) );
		return '' !== $nonce && (bool) wp_verify_nonce( $nonce, self::EXPRESS_NONCE_ACTION );
	}

	/** @param array<string,mixed> $data */
	private static function response_needs_shipping( array $data ): bool {
		if ( array_key_exists( 'needs_shipping', $data ) ) {
			return true === $data['needs_shipping'] || 'yes' === $data['needs_shipping'];
		}

		return function_exists( 'WC' ) && WC()->cart && WC()->cart->needs_shipping();
	}

	/** @param array<string,mixed> $data */
	private static function shipping_rate_count( array $data ): int {
		$packages = $data['shipping_rates'] ?? [];
		if ( ! is_array( $packages ) ) {
			return 0;
		}

		$count = 0;
		foreach ( $packages as $package ) {
			if ( ! is_array( $package ) ) {
				continue;
			}
			$rates = $package['shipping_rates'] ?? [];
			if ( is_array( $rates ) ) {
				$count += count( $rates );
			}
		}
		return $count;
	}

	/** @param array<string,mixed> $context */
	private static function log_failure( string $event, array $context ): void {
		if ( function_exists( 'dtb_security_log' ) ) {
			dtb_security_log( sanitize_key( $event ), $context );
			return;
		}

		if ( function_exists( 'wc_get_logger' ) ) {
			wc_get_logger()->warning( sanitize_key( $event ), [ 'source' => 'dtb-stripe-express-checkout' ] + $context );
		}
	}
}

DTB_ExpressCheckoutShippingReadiness::register();
