<?php
/**
 * Drywall Toolbox — Active Theme functions.php
 *
 * This is the active WordPress theme for elliottm4.sg-host.com. Its sole job is
 * to serve the React SPA as the complete frontend. WordPress and WooCommerce
 * run exclusively as the headless CMS/REST API backend.
 *
 * Architecture:
 *  - WordPress installed at /wp/ subdirectory on the server.
 *  - React SPA build output lives at the site root in /dist/ (one level above
 *    ABSPATH), deployed by GitHub Actions on every push to main.
 *  - Asset manifest at /dist/asset-manifest.json maps logical chunk names to
 *    content-hashed filenames for cache busting.
 *  - WordPress enqueues the React build assets and outputs a window.DTB_CONFIG
 *    bootstrap object so React can read runtime values without hardcoding them.
 *
 * Responsibilities:
 *  1. Minimal theme setup.
 *  2. Enqueue React SPA assets from content-hashed asset manifest.
 *  3. Inject runtime config (window.DTB_CONFIG) into the page.
 *  4. Force all frontend requests to render via index.php (the React shell).
 *  5. Strip unnecessary WordPress head output.
 *
 * Cross-cutting security, CORS, Woo public read, nonce refresh, and admin
 * compatibility policy lives in mu-plugins so production behavior is theme-safe.
 *
 * @package drywall-toolbox
 * @version 2.0.0
 */

defined( 'ABSPATH' ) || exit;


// =============================================================================
// CONSTANTS
// =============================================================================

define( 'DTB_VERSION',   '2.0.0' );
define( 'DTB_DOMAIN',    'drywall-toolbox' );
define( 'DTB_NAMESPACE', 'dtb/v1' );


// =============================================================================
// 1. THEME SETUP
// =============================================================================

add_action( 'after_setup_theme', 'dtb_theme_setup' );
/**
 * Register minimal theme features. This theme renders no PHP templates so
 * WooCommerce template support and post thumbnails are all that is needed.
 */
function dtb_theme_setup(): void {
	load_theme_textdomain( DTB_DOMAIN, get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'woocommerce' );
	add_theme_support( 'wc-product-gallery-zoom' );
	add_theme_support( 'wc-product-gallery-lightbox' );
	add_theme_support( 'wc-product-gallery-slider' );

	// Image sizes consumed by the React frontend via the REST API _images field.
	add_image_size( 'product-thumb',    120,  120,  true  ); // Cart / order line items.
	add_image_size( 'product-card',     480,  480,  true  ); // Product grid cards.
	add_image_size( 'product-hero',     960,  960,  false ); // Product detail main image.
	add_image_size( 'product-zoom',    1600, 1600,  false ); // Lightbox / zoom.
	add_image_size( 'category-banner', 1440,  480,  true  ); // Category page headers.

	// Navigation menus exposed via REST API for React dynamic navigation.
	register_nav_menus(
		[
			'primary'   => __( 'Primary Navigation',   DTB_DOMAIN ),
			'secondary' => __( 'Secondary Navigation', DTB_DOMAIN ),
			'footer'    => __( 'Footer Navigation',    DTB_DOMAIN ),
			'mobile'    => __( 'Mobile Navigation',    DTB_DOMAIN ),
			'account'   => __( 'Account Navigation',   DTB_DOMAIN ),
		]
	);
}


// =============================================================================
// 2. ENQUEUE REACT SPA ASSETS
//
// Reads dist/asset-manifest.json (generated by the React build) to resolve
// content-hashed filenames, then enqueues them in the correct dependency order.
//
// Expected manifest structure (Webpack / CRA):
// {
//   "files": {
//     "main.css":               "/dist/static/css/main.abc123.css",
//     "runtime.js":             "/dist/static/js/runtime.abc123.js",
//     "vendor-react.js":        "/dist/static/js/vendor-react.abc123.js",
//     "vendor.js":              "/dist/static/js/vendor.abc123.js",
//     "common.js":              "/dist/static/js/common.abc123.js",
//     "main.js":                "/dist/static/js/main.abc123.js"
//   }
// }
//
// Vite note: If using Vite, switch to reading dist/.vite/manifest.json and
// adjust the chunk key patterns accordingly. The enqueueing logic below is
// compatible with both; only the manifest path differs.
// =============================================================================

add_action( 'wp_enqueue_scripts', 'dtb_enqueue_react_app' );
/**
 * Enqueue the React SPA CSS and JS chunks in correct dependency order.
 * Falls back gracefully if the manifest does not exist (pre-build state).
 */
function dtb_enqueue_react_app(): void {
	/*
	 * Resolve paths.
	 *
	 * WordPress is installed in /wp/ → ABSPATH ends in /wp/
	 * The React dist/ lives at the website root (one level up).
	 *
	 * Server path: dirname(ABSPATH) . '/dist'
	 * Public URL:  home_url()       . '/dist'
	 */
	$site_root = rtrim( dirname( rtrim( ABSPATH, DIRECTORY_SEPARATOR ) ), DIRECTORY_SEPARATOR );
	$dist_path = $site_root . DIRECTORY_SEPARATOR . 'dist';
	$dist_uri  = rtrim( home_url(), '/' ) . '/dist';
	$manifest  = $dist_path . DIRECTORY_SEPARATOR . 'asset-manifest.json';

	if ( ! file_exists( $manifest ) ) {
		// Build hasn't run yet — fail silently rather than crash the admin.
		if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
			error_log( '[DTB] React asset manifest not found at: ' . $manifest );
		}
		return;
	}

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	$json = file_get_contents( $manifest );
	$data = json_decode( $json, true );

	if ( ! $data || empty( $data['files'] ) || ! is_array( $data['files'] ) ) {
		if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
			error_log( '[DTB] React asset manifest is empty or malformed.' );
		}
		return;
	}

	$files    = $data['files'];
	$enqueued = [];

	// -------------------------------------------------------------------------
	// CSS — enqueue main bundle in <head>. Content-hashed filename → null version
	// disables WordPress ?ver= cache-buster (filename already busts cache).
	// -------------------------------------------------------------------------
	foreach ( $files as $key => $src ) {
		if ( preg_match( '/^main.*\.css$/i', $key ) ) {
			wp_enqueue_style(
				'dtb-app',
				dtb_resolve_asset_url( $src, $dist_uri ),
				[],
				null
			);
			break;
		}
	}

	// -------------------------------------------------------------------------
	// JavaScript — enqueue in strict dependency order:
	//   runtime → vendor-react → vendor → common → main
	//
	// Each handle declares only the deps that were actually enqueued, preventing
	// WordPress warnings about missing dependency handles.
	// -------------------------------------------------------------------------

	/**
	 * Enqueue a single JS chunk if its manifest key matches $pattern.
	 *
	 * @param string   $handle  wp_enqueue_script handle.
	 * @param string   $pattern Regex matched against manifest file keys.
	 * @param string[] $deps    Dependency handles (filtered to enqueued only).
	 */
	$enqueue_chunk = function(
		string $handle,
		string $pattern,
		array  $deps
	) use (
		$files,
		$dist_uri,
		&$enqueued
	): void {
		foreach ( $files as $key => $src ) {
			if ( preg_match( $pattern, $key ) ) {
				wp_enqueue_script(
					$handle,
					dtb_resolve_asset_url( $src, $dist_uri ),
					dtb_filter_enqueued_deps( $deps, $enqueued ),
					null,  // Content-hashed filename already busts cache.
					true   // Load in footer.
				);
				$enqueued[] = $handle;
				break;
			}
		}
	};

	// Webpack runtime chunk — must load first.
	$enqueue_chunk( 'dtb-runtime',      '/^runtime.*\.js$/i',       [] );

	// React and ReactDOM vendor bundle.
	$enqueue_chunk( 'dtb-vendor-react', '/^vendor-react.*\.js$/i',  [ 'dtb-runtime' ] );

	// Other vendor libraries (lodash, axios, etc.).
	// Uses exact match on "vendor.js" to avoid matching "vendor-react.js".
	$enqueue_chunk( 'dtb-vendor',       '/^vendor\.js$/i',           [ 'dtb-runtime' ] );

	// Shared application chunks.
	$enqueue_chunk( 'dtb-common',       '/^common.*\.js$/i',         [ 'dtb-runtime', 'dtb-vendor-react', 'dtb-vendor' ] );

	// Main application entry point — depends on all prior chunks.
	$enqueue_chunk( 'dtb-main',         '/^main.*\.js$/i',           [ 'dtb-runtime', 'dtb-vendor-react', 'dtb-vendor', 'dtb-common' ] );

	// -------------------------------------------------------------------------
	// Runtime config — inline script injected before dtb-main executes.
	// React reads window.DTB_CONFIG on startup for API URLs, nonce, etc.
	// NEVER put sensitive server-side secrets here — this is client-visible.
	// -------------------------------------------------------------------------
	if ( in_array( 'dtb-main', $enqueued, true ) ) {
		$config = [
			// WordPress REST API base URL.
			'wpApiUrl'    => esc_url_raw( home_url( '/wp-json' ) ),

			// WooCommerce REST API base URL.
			'wcApiUrl'    => esc_url_raw( home_url( '/wp-json/wc/v3' ) ),

			// Headless custom namespace base URL.
			'headlessUrl' => esc_url_raw( home_url( '/wp-json/' . DTB_NAMESPACE ) ),

			// WP REST nonce — required for authenticated requests (cart, orders, auth).
			// React should store this and send it as the X-WP-Nonce header.
			'nonce'       => wp_create_nonce( 'wp_rest' ),

			// Nonce refresh URL — React should call this to get a fresh nonce
			// if a request returns a 403 due to an expired nonce (60-min TTL).
			'nonceRefreshUrl' => esc_url_raw( home_url( '/wp-json/' . DTB_NAMESPACE . '/nonce' ) ),

			// Site URLs.
			'siteUrl'     => esc_url( get_site_url() ),
			'homeUrl'     => esc_url( home_url( '/' ) ),

			// Asset base URL — React can use this for any non-bundled static assets.
			'assetsUrl'   => esc_url_raw( home_url( '/dist' ) ),

			// WooCommerce currency info for client-side price formatting.
			'currency'    => class_exists( 'WooCommerce' ) ? get_woocommerce_currency()                              : 'USD',
			'currencySymbol' => class_exists( 'WooCommerce' ) ? html_entity_decode( get_woocommerce_currency_symbol() ) : '$',

			// Build version — React can use this for cache invalidation logic.
			'version'     => DTB_VERSION,

			// Is user logged in? Allows React to skip auth checks on initial render.
			'isLoggedIn'  => is_user_logged_in(),
		];

		wp_add_inline_script(
			'dtb-main',
			'window.DTB_CONFIG = ' . wp_json_encode( $config, JSON_UNESCAPED_SLASHES ) . ';',
			'before'
		);
	}
}

/**
 * Resolve a manifest asset path to a full, correct public URL.
 *
 * The manifest stores values as absolute paths from the domain root, e.g.:
 *   "/dist/static/js/main.abc123.js"
 *
 * We strip the leading /dist/ segment and rebuild the URL from the real
 * $dist_uri so non-root installs and custom domain setups resolve correctly.
 *
 * @param string $manifest_src  Value from asset-manifest.json (path or URL).
 * @param string $dist_uri      Full public URL to the dist/ directory.
 * @return string               Absolute URL safe to pass to wp_enqueue_*.
 */
function dtb_resolve_asset_url( string $manifest_src, string $dist_uri ): string {
	// Already a full URL (CDN, absolute URL in manifest) — use directly.
	if ( str_starts_with( $manifest_src, 'http://' ) || str_starts_with( $manifest_src, 'https://' ) ) {
		return esc_url_raw( $manifest_src );
	}

	// Strip the leading /dist/ portion and any leading slash,
	// then reassemble with the real dist URI.
	// e.g. "/dist/static/js/main.abc.js" → "static/js/main.abc.js"
	$relative = ltrim( preg_replace( '#^.*?/dist/#', '', $manifest_src ), '/' );

	return esc_url_raw( rtrim( $dist_uri, '/' ) . '/' . $relative );
}

/**
 * Filter a dependency list down to only the handles that were actually enqueued.
 *
 * Prevents wp_enqueue_script() from logging "registered script missing" notices
 * when optional chunks (e.g. vendor-react, common) are absent from the manifest.
 *
 * @param string[] $wanted   Desired dependency handles.
 * @param string[] $enqueued Handles confirmed as registered in this request.
 * @return string[]          Filtered list safe to pass to wp_enqueue_script().
 */
function dtb_filter_enqueued_deps( array $wanted, array $enqueued ): array {
	return array_values( array_intersect( $wanted, $enqueued ) );
}


// =============================================================================
// 3. FORCE REACT TEMPLATE
// All public-facing requests render through index.php (the React SPA shell).
// wp-admin, REST API, cron, WP-CLI, and AJAX are explicitly preserved.
// =============================================================================

add_filter( 'template_include', 'dtb_force_react_template', 99 );
/**
 * Return the theme's index.php for all non-admin, non-API requests.
 * index.php contains only the <html> shell; React hydrates the rest.
 *
 * @param string $template Resolved template file path.
 * @return string          index.php or original $template for admin/API.
 */
function dtb_force_react_template( string $template ): string {
	if (
		is_admin() ||
		( defined( 'REST_REQUEST' ) && REST_REQUEST  ) ||
		( defined( 'DOING_CRON' )   && DOING_CRON   ) ||
		( defined( 'WP_CLI' )       && WP_CLI        ) ||
		( defined( 'DOING_AJAX' )   && DOING_AJAX    )
	) {
		return $template;
	}

	// WooCommerce order-pay is a native WC server-rendered page.
	// Return WC's resolved template so the payment gateway renders correctly.
	if ( function_exists( 'is_checkout_pay_page' ) && is_checkout_pay_page() ) {
		return $template;
	}
	if ( function_exists( 'is_wc_endpoint_url' ) && is_wc_endpoint_url( 'order-pay' ) ) {
		return $template;
	}
	// Path-based guard for cases where WC query vars haven't been set yet.
	$request_uri = isset( $_SERVER['REQUEST_URI'] )
		? (string) wp_unslash( $_SERVER['REQUEST_URI'] )
		: '';
	if ( false !== strpos( $request_uri, '/checkout/order-pay/' ) && false !== strpos( $request_uri, 'key=wc_order_' ) ) {
		return $template;
	}

	return get_template_directory() . '/index.php';
}

/**
 * Suppress all frontend asset output from plugins and WordPress core.
 * Nothing renders server-side, so no enqueued assets should reach the page.
 * Our own dtb_enqueue_react_app() runs before this hook at default priority.
 */
add_action( 'wp_enqueue_scripts', 'dtb_dequeue_non_react_assets', 9999 );
function dtb_dequeue_non_react_assets(): void {
	// Order-pay is a native WC server-rendered payment page.
	// All WC payment gateway scripts must load — do not strip anything.
	if ( function_exists( 'is_checkout_pay_page' ) && is_checkout_pay_page() ) {
		return;
	}
	if ( function_exists( 'is_wc_endpoint_url' ) && is_wc_endpoint_url( 'order-pay' ) ) {
		return;
	}
	$request_uri = isset( $_SERVER['REQUEST_URI'] )
		? (string) wp_unslash( $_SERVER['REQUEST_URI'] )
		: '';
	if ( false !== strpos( $request_uri, '/checkout/order-pay/' ) && false !== strpos( $request_uri, 'key=wc_order_' ) ) {
		return;
	}

	global $wp_scripts, $wp_styles;

	// Whitelist of asset handles enqueued by our own dtb_enqueue_react_app().
	$our_handles = [ 'dtb-app', 'dtb-runtime', 'dtb-vendor-react', 'dtb-vendor', 'dtb-common', 'dtb-main' ];

	// Remove all scripts not in our whitelist.
	if ( isset( $wp_scripts->queue ) ) {
		$wp_scripts->queue = array_values( array_intersect( $wp_scripts->queue, $our_handles ) );
	}

	// Remove all styles not in our whitelist.
	if ( isset( $wp_styles->queue ) ) {
		$wp_styles->queue = array_values( array_intersect( $wp_styles->queue, $our_handles ) );
	}
}


// =============================================================================
// 4. CLEAN WORDPRESS HEAD OUTPUT
// Removes WordPress head tags that serve no purpose in a headless SPA context.
// =============================================================================

add_action( 'init', 'dtb_clean_head' );
function dtb_clean_head(): void {
	// WordPress version disclosure.
	remove_action( 'wp_head', 'wp_generator' );
	add_filter( 'the_generator', '__return_empty_string' );

	// Discovery / remote editing protocol links.
	remove_action( 'wp_head', 'rsd_link' );
	remove_action( 'wp_head', 'wlwmanifest_link' );
	remove_action( 'wp_head', 'wp_shortlink_wp_head',           10 );
	remove_action( 'wp_head', 'wp_oembed_add_discovery_links'      );
	remove_action( 'wp_head', 'wp_oembed_add_host_js'              );

	// Pagination links — React Router handles navigation, not WordPress.
	remove_action( 'wp_head', 'adjacent_posts_rel_link_wp_head', 10 );

	// Feed auto-discovery — no server-rendered RSS in headless setup.
	remove_action( 'wp_head', 'feed_links',                       2 );
	remove_action( 'wp_head', 'feed_links_extra',                  3 );

	// DNS prefetch / preconnect hints — React manages its own resource hints.
	remove_action( 'wp_head', 'wp_resource_hints',                 2 );

	// Emoji — unused in React app.
	remove_action( 'wp_head',         'print_emoji_detection_script', 7 );
	remove_action( 'wp_print_styles', 'print_emoji_styles'              );
	add_filter( 'emoji_svg_url',      '__return_false'                   );
}


// Theme policy is intentionally thin: REST/CORS/security/performance hardening
// now lives in mu-plugins so active-theme changes do not change production policy.
